
server:
  port: 8081

internal:
  token: c523db8c7dafcaf567a28d7d910f985ffdfff52d2e5850f18062f8c82e338e6b
  key: X-Internal-Token
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/plan-control
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
