
server:
  port: 8081

api:
  gateway:
    url: http://localhost:8080
security:
  jwt:
    token:
      secret-key: uH12jPqz0W+o+fSde9q5Tf0mXEtmCqKnm2Vp3xczxUg=
      expire-lenght: 3600000
internal:
  token: c523db8c7dafcaf567a28d7d910f985ffdfff52d2e5850f18062f8c82e338e6b
  key: X-Internal-Token
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: plan_control
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
