cors:
  originPatterns: http://localhost:8080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/plan-control
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
