-- public.categories definição

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
                                   created_at timestamp(6) NOT NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   updated_at timestamp(6) NULL,
                                   description varchar(255) NULL,
                                   "name" varchar(255) NULL,
                                   CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.categories OWNER TO postgres;
GRANT ALL ON TABLE public.categories TO postgres;