-- public.products definição

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
                                 speed_download int4 NULL,
                                 speed_upload int4 NULL,
                                 taxa_adesao numeric(38, 2) NULL,
                                 value numeric(38, 2) NULL,
                                 value_wifi numeric(38, 2) NULL,
                                 category_id int8 NULL,
                                 created_at timestamp(6) NOT NULL,
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 updated_at timestamp(6) NULL,
                                 description varchar(255) NULL,
                                 "name" varchar(255) NULL,
                                 CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.products OWNER TO postgres;
GRANT ALL ON TABLE public.products TO postgres;


-- public.products chaves estrangeiras

ALTER TABLE public.products ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);